
name: Sphinx to GitHub pages

on:
  push:
    branches:
      - devops/github_pages

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install sphinx
        pip install numpydoc
        pip install pydata-sphinx-theme
        pip install sphinx-autodoc-typehints
        pip install sphinx-design

    - name: Build HTML
      run: |
        sphinx-build docs _build

    - name: Deploy 
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build
